const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.MoveTo,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.ScrollToObject
	];
};
self.C3_JsPropNameTable = [
	{星空背景: 0},
	{START: 0},
	{Mouse: 0},
	{關卡一: 0},
	{關卡二: 0},
	{關卡三: 0},
	{Sine: 0},
	{TITLE: 0},
	{BACK: 0},
	{星空背景二: 0},
	{裝飾1STAR: 0},
	{卡牌一: 0},
	{淡入淡出: 0},
	{長頸鹿: 0},
	{對話框: 0},
	{對話: 0},
	{Touch: 0},
	{音頻: 0},
	{頁數鈕: 0},
	{第一關: 0},
	{MoveTo: 0},
	{星座介紹: 0},
	{AJAX: 0},
	{遮蔽物: 0},
	{Sprite2: 0},
	{播放: 0},
	{暫停: 0},
	{開始測驗: 0},
	{遊戲介紹: 0},
	{Array: 0},
	{Text: 0},
	{名字: 0},
	{測驗題目: 0},
	{A: 0},
	{B: 0},
	{C: 0},
	{D: 0},
	{Fade: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{第二單元電子書: 0},
	{頁數鈕back: 0},
	{第三單元電子書: 0},
	{正弦: 0},
	{點按提示: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{頁數: 0},
	{TALK: 0},
	{TOUCH: 0},
	{SOUND: 0},
	{星座: 0},
	{Intro: 0},
	{music: 0},
	{i: 0},
	{TT: 0}
];

self.InstanceType = {
	星空背景: class extends self.ITiledBackgroundInstance {},
	START: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	關卡一: class extends self.ISpriteInstance {},
	關卡二: class extends self.ISpriteInstance {},
	關卡三: class extends self.ISpriteInstance {},
	TITLE: class extends self.ISpriteInstance {},
	BACK: class extends self.ISpriteInstance {},
	星空背景二: class extends self.ITiledBackgroundInstance {},
	裝飾1STAR: class extends self.ISpriteInstance {},
	卡牌一: class extends self.ISpriteInstance {},
	長頸鹿: class extends self.ISpriteInstance {},
	對話框: class extends self.ISpriteInstance {},
	對話: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	音頻: class extends self.IInstance {},
	頁數鈕: class extends self.ISpriteInstance {},
	第一關: class extends self.ITextInstance {},
	星座介紹: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	遮蔽物: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	播放: class extends self.ISpriteInstance {},
	暫停: class extends self.ISpriteInstance {},
	開始測驗: class extends self.ISpriteInstance {},
	遊戲介紹: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Text: class extends self.ITextInstance {},
	名字: class extends self.ITextInstance {},
	測驗題目: class extends self.ISpriteInstance {},
	A: class extends self.ISpriteInstance {},
	B: class extends self.ISpriteInstance {},
	C: class extends self.ISpriteInstance {},
	D: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	第二單元電子書: class extends self.ISpriteInstance {},
	頁數鈕back: class extends self.ISpriteInstance {},
	第三單元電子書: class extends self.ISpriteInstance {},
	點按提示: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}